# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('tipodocumentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(auto_now_add=True, db_index=True)),
                ('rut_receptor', models.CharField(db_index=True, max_length=20)),
                ('rut_emisor', models.CharField(db_index=True, max_length=20)),
                ('tipo_envio', models.CharField(db_index=True, max_length=20)),
                ('numero_folio', models.BigIntegerField(db_index=True)),
                ('resolucion_receptor', models.IntegerField(blank=True, null=True)),
                ('resolucion_emisor', models.IntegerField(blank=True, null=True)),
                ('monto', models.BigIntegerField(db_index=True, default=0)),
                ('fecha_emision', models.BigIntegerField(blank=True, null=True)),
                ('fecha_recepcion', models.BigIntegerField(blank=True, null=True)),
                ('estado_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_receptor', models.CharField(blank=True, max_length=100, null=True)),
                ('id_envio', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('correo', models.EmailField(db_index=True, max_length=250)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('opcional1', models.CharField(db_index=True, max_length=255, null=True)),
                ('opcional2', models.CharField(db_index=True, max_length=255, null=True)),
                ('opcional3', models.CharField(db_index=True, max_length=255, null=True)),
                ('xml', models.FileField(blank=True, null=True, upload_to='adjuntos/xml/%Y/%m/%d/%H%M%S')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='adjuntos/pdf/%Y/%m/%d/%H%M%S')),
                ('adjunto1', models.FileField(blank=True, null=True, upload_to='adjuntos/ad1/%Y/%m/%d/%H%M%S')),
                ('smtp_id', models.CharField(blank=True, max_length=200, null=True)),
                ('processed_date', models.BigIntegerField(blank=True, null=True)),
                ('processed_event', models.CharField(blank=True, db_index=True, max_length=240, null=True)),
                ('processed_sg_event_id', models.CharField(blank=True, max_length=240, null=True)),
                ('processed_sg_message_id', models.CharField(blank=True, max_length=240, null=True)),
                ('delivered_date', models.BigIntegerField(blank=True, null=True)),
                ('delivered_event', models.CharField(blank=True, db_index=True, max_length=240, null=True)),
                ('delivered_sg_event_id', models.CharField(blank=True, max_length=240, null=True)),
                ('delivered_sg_message_id', models.CharField(blank=True, max_length=240, null=True)),
                ('delivered_response', models.TextField(blank=True, null=True)),
                ('opened_first_date', models.BigIntegerField(blank=True, null=True)),
                ('opened_last_date', models.BigIntegerField(blank=True, null=True)),
                ('opened_event', models.CharField(blank=True, db_index=True, max_length=240, null=True)),
                ('opened_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('opened_user_agent', models.CharField(blank=True, max_length=240, null=True)),
                ('opened_sg_event_id', models.CharField(blank=True, max_length=240, null=True)),
                ('opened_sg_message_id', models.CharField(blank=True, max_length=240, null=True)),
                ('opened_count', models.IntegerField(blank=True, default=0, null=True)),
                ('dropped_date', models.BigIntegerField(blank=True, null=True)),
                ('dropped_sg_event_id', models.CharField(blank=True, max_length=240, null=True)),
                ('dropped_sg_message_id', models.CharField(blank=True, max_length=240, null=True)),
                ('dropped_reason', models.CharField(blank=True, max_length=240, null=True)),
                ('dropped_event', models.CharField(blank=True, db_index=True, max_length=240, null=True)),
                ('bounce_date', models.BigIntegerField(blank=True, null=True)),
                ('bounce_event', models.CharField(blank=True, db_index=True, max_length=240, null=True)),
                ('bounce_sg_event_id', models.CharField(blank=True, max_length=240, null=True)),
                ('bounce_sg_message_id', models.CharField(blank=True, max_length=240, null=True)),
                ('bounce_reason', models.TextField(blank=True, null=True)),
                ('bounce_status', models.CharField(blank=True, max_length=240, null=True)),
                ('bounce_type', models.CharField(blank=True, max_length=240, null=True)),
                ('unsubscribe_date', models.BigIntegerField(blank=True, null=True)),
                ('unsubscribe_uid', models.CharField(blank=True, max_length=240, null=True)),
                ('unsubscribe_purchase', models.CharField(blank=True, max_length=240, null=True)),
                ('unsubscribe_id', models.CharField(blank=True, max_length=240, null=True)),
                ('unsubscribe_event', models.CharField(blank=True, db_index=True, max_length=240, null=True)),
                ('click_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('click_purchase', models.CharField(blank=True, max_length=240, null=True)),
                ('click_useragent', models.CharField(blank=True, max_length=240, null=True)),
                ('click_event', models.CharField(blank=True, db_index=True, max_length=240, null=True)),
                ('click_email', models.CharField(blank=True, max_length=240, null=True)),
                ('click_date', models.BigIntegerField(blank=True, null=True)),
                ('click_url', models.CharField(blank=True, max_length=240, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
                ('tipo_dte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodocumentos.TipoDocumento')),
            ],
        ),
    ]
