# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='click_useragent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='opened_user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
