# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminacionHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('dias_a_eliminar', models.IntegerField(blank=True, null=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_row_max_length', models.IntegerField()),
                ('report_file_format', models.CharField(choices=[('xlsx', 'xlsx'), ('csv', 'csv'), ('tsv', 'tsv')], max_length=100)),
                ('report_file_zipped', models.BooleanField(default=True)),
                ('events_register', models.BooleanField(default=False)),
                ('events_to_register', models.CharField(default='processed', max_length=255)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding')),
            ],
        ),
        migrations.CreateModel(
            name='SendgridConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, max_length=200)),
                ('api_user', models.CharField(db_index=True, max_length=200)),
                ('api_pass', models.CharField(db_index=True, max_length=200)),
                ('asunto_email_dte', models.EmailField(db_index=True, max_length=240)),
                ('nombre_email_dte', models.CharField(db_index=True, max_length=200)),
                ('asunto_email_reporte', models.EmailField(db_index=True, max_length=240)),
                ('nombre_email_reporte', models.CharField(db_index=True, max_length=240)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding')),
            ],
        ),
        migrations.CreateModel(
            name='SoapWebService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('con_autenticacion', models.BooleanField(default=False)),
                ('usuario_autenticacion', models.CharField(blank=True, max_length=200, null=True)),
                ('clave_autenticacion', models.CharField(blank=True, max_length=200, null=True)),
                ('con_objeto_documento', models.BooleanField(default=False)),
                ('nombre_objeto_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_parametro_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_objeto_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_objeto_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('con_objeto_request', models.BooleanField(default=False)),
                ('nombre_objeto_request', models.CharField(blank=True, max_length=200, null=True)),
                ('solo_default', models.BooleanField(default=False)),
                ('metodo_default', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_default', models.CharField(blank=True, help_text='Lista de parametros ordenados                                             por posici\xf3n en el metodo del Web Service                                             separado por ; sin espacios ejemplo:                                             "rut_emisor;numero_folio;input_date"', max_length=255)),
                ('campos_default', models.CharField(blank=True, max_length=255, null=True)),
                ('con_procesado', models.BooleanField(default=False)),
                ('metodo_procesado', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_procesado', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_procesado', models.CharField(blank=True, max_length=255, null=True)),
                ('con_enviado', models.BooleanField(default=False)),
                ('metodo_enviado', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_enviado', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_enviado', models.CharField(blank=True, max_length=255, null=True)),
                ('con_leido', models.BooleanField(default=False)),
                ('metodo_leido', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_leido', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_leido', models.CharField(blank=True, max_length=255, null=True)),
                ('con_rebotado', models.BooleanField(default=False)),
                ('metodo_rebotado', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_rebotado', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_rebotado', models.CharField(blank=True, max_length=255, null=True)),
                ('con_rechazado', models.BooleanField(default=False)),
                ('metodo_rechazado', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_rechazado', models.CharField(blank=True, max_length=200, null=True)),
                ('campos_rechazado', models.CharField(blank=True, max_length=255, null=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte_url', models.URLField(blank=True, db_index=True)),
                ('asunto_reporte', models.CharField(db_index=True, max_length=240)),
                ('template_html', models.TextField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding')),
            ],
        ),
    ]
