# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_documento', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_documento', models.CharField(max_length=200)),
                ('es_electronico', models.BooleanField()),
            ],
        ),
    ]
